export const DEFAULT_METRIC_SYNC_MONTHS = 3;
export const METRIC_SYNC_CHUNK_DAYS = 30;
export const REVIEW_SYNC_PAGE_SIZE = 50;
export const POST_SYNC_PAGE_SIZE = 100;

export const GBP_DAILY_METRICS = [
  'WEBSITE_CLICKS',
  'CALL_CLICKS',
  'BUSINESS_DIRECTION_REQUESTS',
  'BUSINESS_BOOKINGS',
  'BUSINESS_CONVERSATIONS',
  'BUSINESS_IMPRESSIONS_DESKTOP_MAPS',
  'BUSINESS_IMPRESSIONS_DESKTOP_SEARCH',
  'BUSINESS_IMPRESSIONS_MOBILE_MAPS',
  'BUSINESS_IMPRESSIONS_MOBILE_SEARCH',
] as const;

export type GbpDailyMetric = (typeof GBP_DAILY_METRICS)[number];
